# Generated by Django 2.2 on 2021-01-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='catagory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
