# Generated by Django 3.1.4 on 2021-01-03 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20210102_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='post_date',
            new_name='note_date',
        ),
    ]
