# Generated by Django 3.1.4 on 2021-01-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20210103_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_date',
            new_name='post_date',
        ),
    ]
