# Generated by Django 2.2 on 2021-01-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20210103_0733'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='post_date',
            new_name='note_date',
        ),
    ]
